-- PROJECT: Store Sales Analysis
-- Description: SQL queries for sales, customer, inventory and employee analysis


create database Store_Sales;
use store_sales;


-- ------------------------------------Functional Requirements (Task to do)---------------------------------------

-- --------------------
-- 3.1	Sales Analysis 
-- --------------------
 
-- • Calculate total revenue generated by each store. 
select s.store_name, 
	sum(oi.quantity * oi.list_price) as total_revenue from orders o
join order_items oi on o.order_id = oi.order_id
join stores s on o.store_id = s.store_id
group by s.store_name;


-- • Identify top 5 best-selling products. 
select p.product_id, p.product_name, 
	sum(oi.quantity) as total_sold from order_items oi
join products p on oi.product_id = p.product_id
group by p.product_name, p.product_id
order by total_sold desc
limit 5;


-- • Calculate monthly sales trends to observe seasonality and growth.
 select month(o.order_date) as month, 
	sum(oi.quantity * oi.list_price) as total_sales from orders o
join order_items oi on o.order_id = oi.order_id
group by month(o.order_date)
order by month;


-- • Identify Top-Selling Product per Category
select c.category_name, p.product_name, 
	sum(oi.quantity) as total_sold from order_items oi
join products p on oi.product_id = p.product_id
join categories c on p.category_id = c.category_id
group by c.category_name, p.product_name;


-- • List of Products with Running Total of Sales 
SELECT p.product_name,
	ROUND(SUM(oi.quantity * oi.list_price), 2) AS total_sales,
	ROUND(
        SUM(SUM(oi.quantity * oi.list_price))
        OVER (ORDER BY p.product_name),
		2) AS running_total_sales
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY p.product_name;



-- -----------------------
-- 3.2	Customer Analysis
-- ----------------------- 

-- • Identify customers with the highest purchases. 
select c.customer_id, c.first_name, c.last_name, 
	sum(oi.quantity * oi.list_price) as total_spent from customers c
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
group by c.customer_id, c.first_name, c.last_name
order by total_spent desc
limit 1;


-- • Find customers who have not placed any orders.
SELECT COUNT(*) FROM customers;
SELECT COUNT(DISTINCT customer_id) FROM orders;

 select c.first_name, c.last_name from customers c
left join orders o on c.customer_id = o.customer_id
where o.order_id is null;


-- • Identify customers who have placed at least 3 orders and spent more than $ 25,000. 
select c.customer_id, c.first_name, c.last_name,
    count(o.order_id) as total_orders,
    sum(oi.quantity * oi.list_price) as total_spent from customers c
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
group by c.customer_id, c.first_name, c.last_name
having total_orders >= 3
and total_spent > 25000;



-- --------------------------
-- 3.3	Inventory Management  
-- --------------------------

-- • Identify low-stock products (below 50 items in inventory). 
select p.product_id, p.product_name, sum(st.quantity) as Total_Stocks from products p
join stocks st on p.product_id = st.product_id
group by p.product_id, p.product_name
having Total_Stocks < 50
order by Total_Stocks;



-- -----------------------------------
-- 3.4	Employee Performance Analysis 
-- -----------------------------------

-- • Identify the top 5 employees based on order transactions handled.
select st.first_name, st.last_name, 
	count(o.order_id) as total_orders from staffs st
join orders o on st.staff_id = o.staff_id
group by st.staff_id, st.first_name, st.last_name
order by total_orders desc
limit 5;

 
-- • Identify staff members with the highest number of orders processed.
select st.first_name, st.last_name, 
	count(o.order_id) as total_orders from staffs st
join orders o on st.staff_id = o.staff_id
group by st.staff_id, st.first_name, st.last_name
order by total_orders desc
limit 1;

 
-- • Rank Staff Based on Revenue Generated 
select * from(select s.staff_id, s.first_name, 
	round(sum(oi.quantity * oi.list_price  * (1 - oi.discount)),2) as Revenue_Genrated ,
	rank() over(order by  sum(oi.quantity * oi.list_price  * (1 - oi.discount)) desc) as rnk
from staffs s
join orders o on s.staff_id = o.staff_id
join order_items oi on oi.order_id = o.order_id
group by s.staff_id, s.first_name)T
order by rnk;



-- ------------------------
-- 3.5	Advanced Reporting 
-- ------------------------
 
-- • Rank products by sales volume. 
SELECT p.product_name,
    SUM(oi.quantity) AS sales_volume,
    RANK() OVER (ORDER BY SUM(oi.quantity) DESC) AS product_rank
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name;


-- • Compare Monthly Sales with Previous Month. 
select date_format(o.order_date,"%Y-%M") AS Month,
	Round(sum(oi.quantity * oi.list_price),2) as total_revenue,
	Round(lag(sum(oi.quantity * oi.list_price))
over(order by  date_format(o.order_date,"%Y-%M")),2) as previous_months_sales
from orders o 
join order_items oi on o.order_id = oi.order_id
group by date_format(o.order_date,"%Y-%M");


-- • Assign Row Number to Orders by Each Customer. 
select customer_id, order_id, order_date,
row_number() over (partition by customer_id order by order_date) as Row_no
from orders;
